# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Periplo
email: daniel@corvalan.dev
description: >- # this means to ignore newlines until "baseurl:"
  Bitácora de un viaje forzoso
baseurl: "/periplo" # the subpath of your site, e.g. /blog
url: "https://corvalan.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: corvalanlara
github_username:  corvalanlara

# Build settings
theme: hitchens-theme
plugins:
  - jekyll-feed
# Personal config
timezone: America/Santiago
hide_search: true
hide_credits: true
google_analytics: true
staticman: true
reCaptcha:
  enabled: true
  siteKey: 6Lf_oZspAAAAAGng_RerURa_dReG_GsA3Cxlloe6
  secret: OEWwjnnpwl9o1eibkNDoeBrEla/WINaqtA+lwisYpmDBv5x95eyoaKYB5vJqBaYaZxs9OPL/gduGtMvKED7T2H+xRW6cF9zQ8as4h/OTyKH4JkE7E+3rrj94lwWO+CPX0+EepHQv/owinl6sDuizHNyP/qbZJYgwvwFKxAFPQ8Th1S4CiUPwSRD3K/LMST32dWqq6+MA6H6rx+84EwaHzhZeM5hw8ykUq5uoUoihj5CO7pZGmKzjUMMkJ441+W0B/YIHnCLonBwnmfXDdvoXbOzxOr3rCSeKTRoKkEA/h+kR38HnCEyJH7N97BEJzh3S1GqCi6tvhVydyU6wscm1QA==

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
